web:
  image: registry.docker.fondofbags.com:5005/docker/wordpress:php5.6-apache
  ports:
    - 80
    - 443
  links:
    - db:db
  volumes:
    - ${path_to_wordpress_project}:/var/www/${main_virtual_host}/releases/current
  environment:
    VIRTUAL_HOST: ${main_virtual_host}${additional_virtual_hosts}
  labels:
    rap.host: ${main_virtual_host}${additional_virtual_hosts}
    io.rancher.container.pull_image: always

db:
  image: percona:latest
  ports:
    - 3306
  environment:
    MYSQL_ROOT_PASSWORD: toor
    MYSQL_USER: wordpress
    MYSQL_PASSWORD: wordpress
    MYSQL_DATABASE: wordpress
  labels:
    io.rancher.container.pull_image: always

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
    - 80
  links:
    - db:db
  restart: always
  environment:
    VIRTUAL_HOST: phpmyadmin.${main_virtual_host}
    PMA_HOST: db
  labels:
    rap.host: phpmyadmin.${main_virtual_host}
    io.rancher.container.pull_image: always